// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5t7OK90_OWfWxMOCHvhhGCYn_ZNB7_-g',
    appId: '1:247996277330:web:5982db70e30cc85df4b58b',
    messagingSenderId: '247996277330',
    projectId: 'cinematix-dianprsty',
    authDomain: 'cinematix-dianprsty.firebaseapp.com',
    storageBucket: 'cinematix-dianprsty.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN-Vb7XUzs7B66DidnJ8hgSuXtTBfndhg',
    appId: '1:247996277330:android:a1089e7929bc08b3f4b58b',
    messagingSenderId: '247996277330',
    projectId: 'cinematix-dianprsty',
    storageBucket: 'cinematix-dianprsty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHz-5P2bcPD5ZXP6l8gx1yMh0G-VUJqyQ',
    appId: '1:247996277330:ios:84d6851e1ca15773f4b58b',
    messagingSenderId: '247996277330',
    projectId: 'cinematix-dianprsty',
    storageBucket: 'cinematix-dianprsty.appspot.com',
    iosBundleId: 'com.dianprasetyo.cinematix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHz-5P2bcPD5ZXP6l8gx1yMh0G-VUJqyQ',
    appId: '1:247996277330:ios:84d6851e1ca15773f4b58b',
    messagingSenderId: '247996277330',
    projectId: 'cinematix-dianprsty',
    storageBucket: 'cinematix-dianprsty.appspot.com',
    iosBundleId: 'com.dianprasetyo.cinematix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5t7OK90_OWfWxMOCHvhhGCYn_ZNB7_-g',
    appId: '1:247996277330:web:a17f2754dd8c3098f4b58b',
    messagingSenderId: '247996277330',
    projectId: 'cinematix-dianprsty',
    authDomain: 'cinematix-dianprsty.firebaseapp.com',
    storageBucket: 'cinematix-dianprsty.appspot.com',
  );
}
